apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    app: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
       -
        env:
         -
          name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: db-user
         -
          name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: db-password
         -
          name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: server-name
         -
          name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: secret-db
              key: db-name
        name: poi
        image: registrynpi4760.azurecr.io/tripinsights/poi:latest
        ports:
         - containerPort: 80