kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-full-access
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-user-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-user-full-access
subjects:
- kind: User
  namespace: web
  name: ab74788e-0134-4521-9a99-38ffb2fcf77c