kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-user-full-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-user-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-user-full-access
subjects:
- kind: User
  namespace: api
  name: 1c16fae8-acb9-41f5-a161-ce442b0fb5bf