apiVersion: v1
kind: Secret
metadata:
    name: secret-db
    namespace: api
type: Opaque
stringData:
    db-user: sqladminnPi4760
    db-password: Canada@5960
    db-name: mydrivingDB
    server-name: sqlservernpi4760.database.windows.net